# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39a410fa82011e49071a693b471dcbfa8da866f925e4833e4cfb689b6f359ea6273677c15e0c01f0d03809c93877e8540c35c5271b7b4356c30c9489485efd6

test:
  secret_key_base: e9c8c49f0508d54adf9631f999e61e9efef3cc4e39878f1b95ed9e57c3b5e6bade5c21dcb303db01f59ed777896035adafbe3853f119cc241e4681fdcf9f558e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
